### ISSUE TITLE
KeePassXC's broadcast messages are not supported

### ISSUE THREAD

**Issue by varjolintu** [varjolintu/keepassxc-proxy-rust#14]
For the proxy to have 100% support with KeePassXC the support for its broadcast messages are missing.
It's necessary to listen the `database-locked` and `database-unlocked` messages. Without those the extension cannot know if database has been changed from/to locked/unlocked or if user has changed to a different database.

**Comment by WhyNotHugo** [comment]
Currently the proxy tries to respect the request<>response cycle of messages, but broadcasts don't follow this pattern.

I wonder if the proxy could simply be "dumber" and just have two threads: one for stdin and another for stdout, and continuously send messages back and forth without caring much about ordering.

**Comment by varjolintu** [comment]
@WhyNotHugo It should definitely work like that, if it's possible to implement.
