### ISSUE TITLE
Start making releases

### ISSUE THREAD

**Issue by jirutka** [varjolintu/keepassxc-proxy-rust#18]
Can you please start making releases, i.e. start bumping the package version and creating release tags? I’ve packaged this project for Alpine Linux ([keepassxc-proxy-static](https://pkgs.alpinelinux.org/packages?name=keepassxc-proxy-static)) and the absence of real version number is not optimal.

**Comment by varjolintu** [comment]
Sure.

**Comment by jirutka** [comment]
Thanks!
