### ISSUE TITLE
Add support for Passkey

### ISSUE THREAD

**Issue by jirutka** [varjolintu/keepassxc-proxy-rust#22]
Can you please implement support for Passkey (see [KeePassXC Protocol](https://github.com/keepassxreboot/keepassxc-browser/blob/develop/keepassxc-protocol.md))?

**Comment by varjolintu** [comment]
It should be already supported. The proxy only transfers messages between the extension and KeePassXC. It doesn't handle the message content.

**Comment by jirutka** [comment]
You’re right, the problem was that I didn’t have KeepassXC built with passkey support.
