### ISSUE TITLE
Socket has moved on latest keepassxc master

### ISSUE THREAD

**Issue by WhyNotHugo** [varjolintu/keepassxc-proxy-rust#8]
The socket has moved to its own directory to ease integration with sandboxed browsers.

See https://github.com/keepassxreboot/keepassxc/pull/8030 and https://github.com/keepassxreboot/keepassxc/issues/8018

The TLDR is that the socket is now located in `$XDG_RUNTIME_DIR/app/org.keepassxc.KeePassXC/org.keepassxc.KeePassXC.BrowserServer`

**Comment by varjolintu** [comment]
This will apply only for KeePassXC 2.7.2. Everyone using the older version might be in trouble.

**Comment by WhyNotHugo** [comment]
True. A good approach would be to try the new path, if that doesn't exist try the old path.
